const a1Questions = [
  { id: 1, question: "My name ___ Alex.", options: ["am", "is", "are", "be"], answer: 1, topic: "Verb to be" },
  { id: 2, question: "They ___ from Uzbekistan.", options: ["is", "am", "are", "be"], answer: 2, topic: "Verb to be" },
  { id: 3, question: "I ___ a student.", options: ["are", "is", "am", "be"], answer: 2, topic: "Verb to be" },
  { id: 4, question: "She ___ two brothers.", options: ["have", "has", "is having", "having"], answer: 1, topic: "Have/has" },
  { id: 5, question: "We ___ breakfast at 7 every day.", options: ["have", "has", "having", "are have"], answer: 0, topic: "Present Simple" },
  { id: 6, question: "Tom ___ football on Saturdays.", options: ["play", "plays", "playing", "is play"], answer: 1, topic: "Present Simple" },
  { id: 7, question: "My parents ___ in Tashkent.", options: ["lives", "live", "living", "is live"], answer: 1, topic: "Present Simple" },
  { id: 8, question: "___ you like coffee?", options: ["Are", "Do", "Does", "Is"], answer: 1, topic: "Present Simple questions" },
  { id: 9, question: "___ she work here?", options: ["Do", "Does", "Is", "Are"], answer: 1, topic: "Present Simple questions" },
  { id: 10, question: "He ___ watch TV in the morning.", options: ["don't", "doesn't", "isn't", "not"], answer: 1, topic: "Present Simple negative" },
  { id: 11, question: "Listen! The baby ___.", options: ["cries", "is crying", "cry", "crying"], answer: 1, topic: "Present Continuous" },
  { id: 12, question: "We ___ English now.", options: ["study", "studies", "are studying", "is studying"], answer: 2, topic: "Present Continuous" },
  { id: 13, question: "I ___ dinner at the moment.", options: ["cook", "am cooking", "cooks", "cooking"], answer: 1, topic: "Present Continuous" },
  { id: 14, question: "___ they playing outside?", options: ["Do", "Does", "Are", "Is"], answer: 2, topic: "Present Continuous questions" },
  { id: 15, question: "She ___ wearing a blue jacket today.", options: ["is", "are", "does", "has"], answer: 0, topic: "Present Continuous" },
  { id: 16, question: "Yesterday I ___ at home.", options: ["am", "was", "were", "be"], answer: 1, topic: "Past Simple of be" },
  { id: 17, question: "They ___ very tired last night.", options: ["was", "were", "are", "is"], answer: 1, topic: "Past Simple of be" },
  { id: 18, question: "We ___ a movie yesterday.", options: ["watch", "watched", "watches", "watching"], answer: 1, topic: "Past Simple" },
  { id: 19, question: "He ___ to school by bus yesterday.", options: ["go", "goes", "went", "going"], answer: 2, topic: "Past Simple" },
  { id: 20, question: "I ___ my keys this morning.", options: ["lose", "lost", "loses", "losing"], answer: 1, topic: "Past Simple" },
  { id: 21, question: "___ you visit your grandmother last week?", options: ["Did", "Do", "Were", "Does"], answer: 0, topic: "Past Simple questions" },
  { id: 22, question: "She ___ like the food.", options: ["didn't", "doesn't", "wasn't", "not"], answer: 0, topic: "Past Simple negative" },
  { id: 23, question: "They didn't ___ the answer.", options: ["knew", "know", "knows", "knowing"], answer: 1, topic: "Past Simple negative" },
  { id: 24, question: "There ___ a book on the table.", options: ["are", "were", "is", "be"], answer: 2, topic: "There is/are" },
  { id: 25, question: "There ___ three students in the room.", options: ["is", "are", "was", "be"], answer: 1, topic: "There is/are" },
  { id: 26, question: "I have ___ apple.", options: ["a", "an", "the", "some"], answer: 1, topic: "Articles" },
  { id: 27, question: "He is ___ teacher.", options: ["a", "an", "the", "some"], answer: 0, topic: "Articles" },
  { id: 28, question: "___ sun is very bright today.", options: ["A", "An", "The", "Some"], answer: 2, topic: "Articles" },
  { id: 29, question: "I need ___ water.", options: ["a", "an", "some", "many"], answer: 2, topic: "Countable/uncountable nouns" },
  { id: 30, question: "There are ___ books on my desk.", options: ["much", "a little", "many", "any"], answer: 2, topic: "Quantifiers" },
  { id: 31, question: "We don't have ___ milk.", options: ["many", "much", "a few", "few"], answer: 1, topic: "Quantifiers" },
  { id: 32, question: "I have ___ friends in my class.", options: ["a lot of", "much", "little", "any"], answer: 0, topic: "Quantifiers" },
  { id: 33, question: "There is ___ rice left.", options: ["a few", "a little", "many", "few"], answer: 1, topic: "Quantifiers" },
  { id: 34, question: "This is ___ bag.", options: ["me", "my", "I", "mine"], answer: 1, topic: "Possessive adjectives" },
  { id: 35, question: "That phone is ___.", options: ["her", "hers", "she", "their"], answer: 1, topic: "Possessive pronouns" },
  { id: 36, question: "These are ___ shoes.", options: ["John", "John's", "Johns", "John is"], answer: 1, topic: "Possessive nouns" },
  { id: 37, question: "I can ___ English.", options: ["speaks", "speak", "speaking", "to speak"], answer: 1, topic: "Can" },
  { id: 38, question: "___ you swim?", options: ["Can", "Are", "Do", "Have"], answer: 0, topic: "Can" },
  { id: 39, question: "You ___ smoke here.", options: ["can", "can't", "are", "do"], answer: 1, topic: "Can/can't" },
  { id: 40, question: "You ___ do your homework tonight.", options: ["must", "mustn't", "can", "are"], answer: 0, topic: "Must" },
  { id: 41, question: "You ___ be late for the exam.", options: ["must", "mustn't", "can", "have"], answer: 1, topic: "Must/mustn't" },
  { id: 42, question: "We ___ wear a uniform at school.", options: ["have to", "has to", "having to", "are have"], answer: 0, topic: "Have to" },
  { id: 43, question: "She ___ get up early every day.", options: ["have to", "has to", "must to", "is have"], answer: 1, topic: "Have to" },
  { id: 44, question: "The bank is ___ the supermarket.", options: ["next to", "next", "between to", "at next"], answer: 0, topic: "Prepositions of place" },
  { id: 45, question: "The cat is ___ the table.", options: ["on", "at", "to", "from"], answer: 0, topic: "Prepositions of place" },
  { id: 46, question: "I go to school ___ Monday.", options: ["in", "on", "at", "from"], answer: 1, topic: "Time prepositions" },
  { id: 47, question: "My birthday is ___ July.", options: ["on", "at", "in", "to"], answer: 2, topic: "Time prepositions" },
  { id: 48, question: "The lesson starts ___ 9 o'clock.", options: ["in", "on", "at", "from"], answer: 2, topic: "Time prepositions" },
  { id: 49, question: "This book is ___ than that one.", options: ["cheap", "cheaper", "cheapest", "more cheap"], answer: 1, topic: "Comparatives" },
  { id: 50, question: "Mount Everest is ___ mountain in the world.", options: ["high", "higher", "the highest", "highest than"], answer: 2, topic: "Superlatives" },
];

export default a1Questions;
