const a2Questions = [
  { id: 1, question: "I ___ this film before.", options: ["see", "saw", "have seen", "am seeing"], answer: 2, topic: "Present Perfect" },
  { id: 2, question: "She ___ to London last year.", options: ["has gone", "went", "has been", "goes"], answer: 1, topic: "Past Simple vs Present Perfect" },
  { id: 3, question: "We ___ here since 2022.", options: ["live", "lived", "have lived", "are living"], answer: 2, topic: "Present Perfect with since" },
  { id: 4, question: "He has worked here ___ three months.", options: ["since", "for", "from", "during"], answer: 1, topic: "Present Perfect with for" },
  { id: 5, question: "They ___ dinner when I arrived.", options: ["have", "were having", "are having", "had have"], answer: 1, topic: "Past Continuous" },
  { id: 6, question: "While I was studying, my brother ___ music.", options: ["listened", "was listening to", "has listened", "listens"], answer: 1, topic: "Past Continuous" },
  { id: 7, question: "I ___ my homework before I went out.", options: ["finished", "had finished", "have finished", "finish"], answer: 1, topic: "Past Perfect" },
  { id: 8, question: "By the time we arrived, the train ___.", options: ["left", "has left", "had left", "leaves"], answer: 2, topic: "Past Perfect" },
  { id: 9, question: "Look at those clouds! It ___.", options: ["rains", "is going to rain", "will raining", "rain"], answer: 1, topic: "Be going to" },
  { id: 10, question: "I think people ___ more electric cars in the future.", options: ["use", "will use", "used", "are use"], answer: 1, topic: "Will" },
  { id: 11, question: "We ___ visit our cousins this weekend; the tickets are booked.", options: ["are going to", "will to", "going", "would"], answer: 0, topic: "Future forms" },
  { id: 12, question: "You ___ see a doctor if you feel worse.", options: ["should", "shouldn't", "mustn't", "couldn't"], answer: 0, topic: "Should" },
  { id: 13, question: "You ___ park here; it is forbidden.", options: ["must", "mustn't", "should", "could"], answer: 1, topic: "Mustn't" },
  { id: 14, question: "___ I borrow your pen?", options: ["Must", "Could", "Should", "Have"], answer: 1, topic: "Polite requests" },
  { id: 15, question: "You ___ bring an umbrella; it might rain.", options: ["should", "mustn't", "can't", "wouldn't"], answer: 0, topic: "Should" },
  { id: 16, question: "She ___ be at home; I saw her car outside.", options: ["must", "can't", "shouldn't", "wouldn't"], answer: 0, topic: "Modal deduction" },
  { id: 17, question: "He ___ be the new teacher. I'm not sure.", options: ["must", "might", "has to", "should"], answer: 1, topic: "Modal possibility" },
  { id: 18, question: "I ___ swim when I was five.", options: ["can", "could", "must", "may"], answer: 1, topic: "Could for past ability" },
  { id: 19, question: "There isn't ___ sugar left.", options: ["many", "much", "a few", "few"], answer: 1, topic: "Quantifiers" },
  { id: 20, question: "I bought ___ oranges at the market.", options: ["much", "a little", "some", "any"], answer: 2, topic: "Quantifiers" },
  { id: 21, question: "There are ___ students in the library today.", options: ["a little", "a few", "much", "any"], answer: 1, topic: "Quantifiers" },
  { id: 22, question: "I don't have ___ money with me.", options: ["many", "much", "a few", "few"], answer: 1, topic: "Quantifiers" },
  { id: 23, question: "This exercise is ___ difficult for me to finish quickly.", options: ["too", "enough", "such", "very enough"], answer: 0, topic: "Too" },
  { id: 24, question: "The room is big ___ for twenty people.", options: ["too", "enough", "so", "such"], answer: 1, topic: "Enough" },
  { id: 25, question: "It was ___ cold that we stayed inside.", options: ["such", "so", "too much", "enough"], answer: 1, topic: "So" },
  { id: 26, question: "It was ___ interesting book that I read it twice.", options: ["so", "such an", "too", "enough"], answer: 1, topic: "Such" },
  { id: 27, question: "I enjoy ___ documentaries.", options: ["watch", "to watch", "watching", "watched"], answer: 2, topic: "Gerund" },
  { id: 28, question: "She decided ___ abroad.", options: ["study", "studying", "to study", "studied"], answer: 2, topic: "Infinitive" },
  { id: 29, question: "He wants ___ a new language.", options: ["learn", "learning", "to learn", "learned"], answer: 2, topic: "Infinitive" },
  { id: 30, question: "I don't mind ___ early.", options: ["get up", "to get up", "getting up", "got up"], answer: 2, topic: "Gerund" },
  { id: 31, question: "The woman ___ lives next door is a doctor.", options: ["which", "who", "where", "what"], answer: 1, topic: "Relative clauses" },
  { id: 32, question: "This is the place ___ we met.", options: ["who", "where", "whose", "what"], answer: 1, topic: "Relative clauses" },
  { id: 33, question: "That's the man ___ car was stolen.", options: ["who", "which", "whose", "where"], answer: 2, topic: "Relative clauses" },
  { id: 34, question: "If it rains, we ___ at home.", options: ["stay", "will stay", "would stay", "stayed"], answer: 1, topic: "First conditional" },
  { id: 35, question: "If I had more time, I ___ another language.", options: ["learn", "will learn", "would learn", "learned"], answer: 2, topic: "Second conditional" },
  { id: 36, question: "If you heat ice, it ___.", options: ["melts", "will melt", "would melt", "melted"], answer: 0, topic: "Zero conditional" },
  { id: 37, question: "I ___ get up early, but now I do.", options: ["used to", "use to", "was used to", "used"], answer: 0, topic: "Used to" },
  { id: 38, question: "There used to ___ a cinema here.", options: ["be", "being", "was", "been"], answer: 0, topic: "Used to" },
  { id: 39, question: "She is interested ___ photography.", options: ["on", "at", "in", "for"], answer: 2, topic: "Prepositions" },
  { id: 40, question: "I'm good ___ solving puzzles.", options: ["at", "in", "on", "for"], answer: 0, topic: "Prepositions" },
  { id: 41, question: "He arrived ___ the airport at six.", options: ["at", "in", "on", "to"], answer: 0, topic: "Prepositions" },
  { id: 42, question: "This car is ___ than mine.", options: ["more comfortable", "comfortabler", "most comfortable", "comfortably"], answer: 0, topic: "Comparatives" },
  { id: 43, question: "That was the ___ meal I've had this year.", options: ["better", "best", "good", "most better"], answer: 1, topic: "Superlatives" },
  { id: 44, question: "I've already ___ my room.", options: ["clean", "cleaned", "cleaning", "cleans"], answer: 1, topic: "Present Perfect" },
  { id: 45, question: "Have you ___ been to Korea?", options: ["ever", "never", "yet already", "since"], answer: 0, topic: "Present Perfect adverbs" },
  { id: 46, question: "She hasn't finished her work ___.", options: ["already", "yet", "ever", "since"], answer: 1, topic: "Present Perfect adverbs" },
  { id: 47, question: "We ___ go to the beach tomorrow if the weather is good.", options: ["might", "mustn't", "can't", "shouldn't"], answer: 0, topic: "Modal possibility" },
  { id: 48, question: "He asked me ___ I liked the movie.", options: ["if", "what", "that", "where"], answer: 0, topic: "Reported questions" },
  { id: 49, question: "She told me ___ the window.", options: ["close", "closing", "to close", "closed"], answer: 2, topic: "Reported commands" },
  { id: 50, question: "I have known my best friend ___ we were children.", options: ["for", "since", "during", "from"], answer: 1, topic: "Since and For" },
];

export default a2Questions;
