const b1Questions = [
  { id: 1, question: "I _____ my homework yet.", options: ["didn't finish", "haven't finished", "don't finish", "wasn't finishing"], answer: 1, topic: "Present Perfect" },
  { id: 2, question: "When I called her, she _____ dinner.", options: ["cooked", "was cooking", "has cooked", "cooks"], answer: 1, topic: "Past Continuous" },
  { id: 3, question: "If it rains tomorrow, we _____ at home.", options: ["stay", "will stay", "would stay", "stayed"], answer: 1, topic: "First Conditional" },
  { id: 4, question: "If I had more free time, I _____ another language.", options: ["learn", "will learn", "would learn", "learned"], answer: 2, topic: "Second Conditional" },
  { id: 5, question: "If she had studied harder, she _____ the exam.", options: ["passes", "would pass", "would have passed", "passed"], answer: 2, topic: "Third Conditional" },
  { id: 6, question: "You _____ wear a seat belt in a car.", options: ["must", "might", "could", "would"], answer: 0, topic: "Modals" },
  { id: 7, question: "The new bridge _____ last year.", options: ["built", "was built", "has built", "is building"], answer: 1, topic: "Passive Voice" },
  { id: 8, question: "He said that he _____ tired.", options: ["is", "was", "will be", "has been"], answer: 1, topic: "Reported Speech" },
  { id: 9, question: "She asked me where I _____.", options: ["live", "lived", "am living", "will live"], answer: 1, topic: "Reported Questions" },
  { id: 10, question: "I enjoy _____ books in my free time.", options: ["read", "to read", "reading", "to reading"], answer: 2, topic: "Gerund" },
  { id: 11, question: "I decided _____ early.", options: ["leave", "leaving", "to leave", "left"], answer: 2, topic: "Infinitive" },
  { id: 12, question: "The woman _____ lives next door is a doctor.", options: ["which", "where", "who", "whose"], answer: 2, topic: "Relative Clauses" },
  { id: 13, question: "There aren't _____ apples left.", options: ["much", "many", "a little", "any of"], answer: 1, topic: "Quantifiers" },
  { id: 14, question: "I'm interested _____ learning Spanish.", options: ["at", "on", "in", "for"], answer: 2, topic: "Prepositions" },
  { id: 15, question: "This book is _____ than the one I read yesterday.", options: ["interesting", "more interesting", "most interesting", "interestingly"], answer: 1, topic: "Comparatives" },
  { id: 16, question: "She is the _____ student in the class.", options: ["more careful", "careful", "most careful", "carefully"], answer: 2, topic: "Superlatives" },
  { id: 17, question: "I _____ play football when I was younger.", options: ["used to", "use to", "was used", "would to"], answer: 0, topic: "Used To" },
  { id: 18, question: "When we arrived, the film _____.", options: ["already started", "had already started", "has already started", "starts"], answer: 1, topic: "Past Perfect" },
  { id: 19, question: "Look at those clouds. It _____ rain.", options: ["will", "is going to", "would", "has"], answer: 1, topic: "Future Forms" },
  { id: 20, question: "I think she _____ pass the exam.", options: ["will", "is", "has", "was"], answer: 0, topic: "Future Forms" },
  { id: 21, question: "It was _____ interesting film that I watched it twice.", options: ["so", "such", "such an", "too"], answer: 2, topic: "So and Such" },
  { id: 22, question: "The bag is light _____ to carry easily.", options: ["enough", "too", "so", "such"], answer: 0, topic: "Enough" },
  { id: 23, question: "You should _____ more water.", options: ["drink", "drinking", "to drink", "drank"], answer: 0, topic: "Modals" },
  { id: 24, question: "We have lived here _____ 2020.", options: ["for", "since", "during", "from"], answer: 1, topic: "Since and For" },
  { id: 25, question: "She has worked here _____ three years.", options: ["since", "from", "for", "during"], answer: 2, topic: "Since and For" },
  { id: 26, question: "I haven't seen him _____ Monday.", options: ["for", "since", "during", "at"], answer: 1, topic: "Since and For" },
  { id: 27, question: "There is _____ milk in the fridge.", options: ["a few", "a little", "many", "few"], answer: 1, topic: "Quantifiers" },
  { id: 28, question: "We don't have _____ information about the problem.", options: ["many", "much", "few", "a few"], answer: 1, topic: "Quantifiers" },
  { id: 29, question: "You _____ smoke in this building.", options: ["mustn't", "don't have", "might not", "couldn't"], answer: 0, topic: "Modals" },
  { id: 30, question: "He _____ be at home; the lights are on.", options: ["must", "can't", "shouldn't", "wouldn't"], answer: 0, topic: "Modal Deduction" },
  { id: 31, question: "She _____ speak three languages when she was ten.", options: ["can", "could", "must", "should"], answer: 1, topic: "Past Ability" },
  { id: 32, question: "The emails _____ every morning.", options: ["check", "are checked", "checked", "are checking"], answer: 1, topic: "Passive Voice" },
  { id: 33, question: "He told me _____ the door.", options: ["close", "closing", "to close", "closed"], answer: 2, topic: "Reported Commands" },
  { id: 34, question: "I don't know _____ she will come.", options: ["that", "if", "what", "where"], answer: 1, topic: "Reported Questions" },
  { id: 35, question: "The man _____ car was stolen called the police.", options: ["who", "which", "whose", "where"], answer: 2, topic: "Relative Clauses" },
  { id: 36, question: "I have never _____ such a beautiful place.", options: ["see", "saw", "seen", "seeing"], answer: 2, topic: "Present Perfect" },
  { id: 37, question: "They _____ dinner when the phone rang.", options: ["had", "were having", "have had", "are having"], answer: 1, topic: "Past Continuous" },
  { id: 38, question: "If you study hard, you _____ improve.", options: ["would", "will", "would have", "had"], answer: 1, topic: "First Conditional" },
  { id: 39, question: "If I were you, I _____ apologize.", options: ["will", "would", "have", "am"], answer: 1, topic: "Second Conditional" },
  { id: 40, question: "She said she _____ already finished the work.", options: ["has", "had", "will have", "is"], answer: 1, topic: "Reported Speech" },
  { id: 41, question: "This exercise is _____ difficult for me.", options: ["too", "enough", "such", "so a"], answer: 0, topic: "Too and Enough" },
  { id: 42, question: "He isn't old _____ to drive.", options: ["too", "enough", "so", "such"], answer: 1, topic: "Enough" },
  { id: 43, question: "This is the restaurant _____ we had dinner.", options: ["who", "where", "which", "whose"], answer: 1, topic: "Relative Clauses" },
  { id: 44, question: "I remember _____ him at the party.", options: ["meet", "to meet", "meeting", "met"], answer: 2, topic: "Gerund and Infinitive" },
  { id: 45, question: "Don't forget _____ the lights off.", options: ["turn", "turning", "to turn", "turned"], answer: 2, topic: "Gerund and Infinitive" },
  { id: 46, question: "We _____ go to the cinema tonight if we finish early.", options: ["might", "mustn't", "can't", "shouldn't"], answer: 0, topic: "Modal Possibility" },
  { id: 47, question: "The homework _____ by the students yesterday.", options: ["completed", "was completed", "is completed", "completes"], answer: 1, topic: "Passive Voice" },
  { id: 48, question: "She asked me _____ I could help her.", options: ["that", "if", "what", "where"], answer: 1, topic: "Reported Speech" },
  { id: 49, question: "I've been studying English _____ two years.", options: ["since", "for", "from", "during"], answer: 1, topic: "Since and For" },
  { id: 50, question: "He is _____ person I've ever met.", options: ["the kindest", "kinder", "kind", "more kind"], answer: 0, topic: "Superlatives" },
];

export default b1Questions;
