const b2Questions = [
  { id: 1, question: "By the time we arrived, the meeting _____.", options: ["had already started", "has already started", "already starts", "was already starting"], answer: 0, topic: "Past Perfect" },
  { id: 2, question: "If I _____ about the problem earlier, I would have helped.", options: ["knew", "had known", "would know", "have known"], answer: 1, topic: "Third Conditional" },
  { id: 3, question: "She _____ have forgotten about the appointment; she wrote it in her diary.", options: ["must", "can't", "should", "might"], answer: 1, topic: "Modal Deduction" },
  { id: 4, question: "The project _____ by the end of next month.", options: ["will complete", "will have been completed", "has completed", "is completing"], answer: 1, topic: "Future Perfect Passive" },
  { id: 5, question: "I'd rather you _____ that information with anyone.", options: ["don't share", "didn't share", "won't share", "haven't shared"], answer: 1, topic: "Would Rather" },
  { id: 6, question: "He denied _____ the confidential document.", options: ["to copy", "copy", "copying", "to copying"], answer: 2, topic: "Gerund" },
  { id: 7, question: "Not only _____ late, but he also forgot the documents.", options: ["he arrived", "did he arrive", "he did arrive", "arrived he"], answer: 1, topic: "Inversion" },
  { id: 8, question: "The woman _____ car was stolen reported it immediately.", options: ["who", "which", "whose", "whom"], answer: 2, topic: "Relative Clauses" },
  { id: 9, question: "I wish I _____ more carefully before signing the contract.", options: ["read", "had read", "have read", "would read"], answer: 1, topic: "Wish" },
  { id: 10, question: "The manager suggested that the report _____ rewritten.", options: ["is", "was", "be", "being"], answer: 2, topic: "Subjunctive" },
  { id: 11, question: "She accused him _____ lying to her.", options: ["for", "of", "about", "with"], answer: 1, topic: "Dependent Prepositions" },
  { id: 12, question: "Hardly _____ the speech when the lights went out.", options: ["he had started", "had he started", "he started", "did he start"], answer: 1, topic: "Inversion" },
  { id: 13, question: "You _____ told me earlier. I could have helped.", options: ["should", "should have", "must", "might"], answer: 1, topic: "Modal Perfect" },
  { id: 14, question: "The new policy is expected _____.", options: ["introducing", "to introduce", "to be introduced", "being introduced"], answer: 2, topic: "Passive Infinitive" },
  { id: 15, question: "Despite _____ exhausted, she continued working.", options: ["being", "be", "was", "to be"], answer: 0, topic: "Gerund" },
  { id: 16, question: "If only I _____ his advice at the time.", options: ["follow", "followed", "had followed", "would follow"], answer: 2, topic: "If Only" },
  { id: 17, question: "The company is believed ____ financial difficulties.", options: ["to face", "facing", "face", "to be facing"], answer: 3, topic: "Reporting Structures" },
  { id: 18, question: "She said she _____ the report the following day.", options: ["will finish", "would finish", "finishes", "has finished"], answer: 1, topic: "Reported Speech" },
  { id: 19, question: "No sooner _____ home than it started raining.", options: ["I had arrived", "had I arrived", "I arrived", "did I arrive"], answer: 1, topic: "Inversion" },
  { id: 20, question: "We need to find a solution _____ everyone can agree.", options: ["which", "where", "to which", "what"], answer: 2, topic: "Relative Clauses" },
  { id: 21, question: "He isn't here. He _____ gone home already.", options: ["must have", "should", "would", "can't have"], answer: 0, topic: "Modal Perfect" },
  { id: 22, question: "I regret _____ you that your application was unsuccessful.", options: ["informing", "to inform", "inform", "informed"], answer: 1, topic: "Gerund and Infinitive" },
  { id: 23, question: "The more you practise, _____ your pronunciation becomes.", options: ["better", "the better", "the best", "more better"], answer: 1, topic: "Comparatives" },
  { id: 24, question: "It was _____ difficult exam that many students complained.", options: ["so", "such", "such a", "so a"], answer: 2, topic: "So and Such" },
  { id: 25, question: "He speaks as though he _____ everything about the subject.", options: ["knows", "knew", "had known", "will know"], answer: 1, topic: "As Though" },
  { id: 26, question: "The house needs ____ before it can be sold.", options: ["renovate", "renovating", "to renovating", "renovated"], answer: 1, topic: "Need + Gerund" },
  { id: 27, question: "I'd rather _____ at home than go out tonight.", options: ["staying", "stay", "to stay", "stayed"], answer: 1, topic: "Would Rather" },
  { id: 28, question: "Under no circumstances _____ this information be shared.", options: ["should", "it should", "should it", "it"], answer: 0, topic: "Inversion" },
  { id: 29, question: "She succeeded _____ persuading them to change their decision.", options: ["at", "in", "on", "for"], answer: 1, topic: "Dependent Prepositions" },
  { id: 30, question: "Had I known the truth, I _____ differently.", options: ["would act", "will act", "would have acted", "acted"], answer: 2, topic: "Third Conditional" },
  { id: 31, question: "The scientist's findings are thought ____ significant.", options: ["being", "to be", "be", "to being"], answer: 1, topic: "Reporting Structures" },
  { id: 32, question: "He asked me whether I _____ the document.", options: ["had received", "have received", "receive", "will receive"], answer: 0, topic: "Reported Questions" },
  { id: 33, question: "She would have passed if she _____ harder.", options: ["studied", "had studied", "would study", "has studied"], answer: 1, topic: "Mixed Conditionals" },
  { id: 34, question: "It's high time you _____ responsibility for your actions.", options: ["take", "took", "have taken", "will take"], answer: 1, topic: "It's High Time" },
  { id: 35, question: "The article is worth _____ in detail.", options: ["read", "to read", "reading", "to reading"], answer: 2, topic: "Gerund" },
  { id: 36, question: "By next June, I _____ here for five years.", options: ["will work", "will have been working", "am working", "have worked"], answer: 1, topic: "Future Perfect Continuous" },
  { id: 37, question: "There is little point _____ with someone who refuses to listen.", options: ["argue", "to argue", "arguing", "argued"], answer: 2, topic: "Gerund" },
  { id: 38, question: "The project was cancelled, _____ surprised everyone.", options: ["that", "what", "which", "where"], answer: 2, topic: "Non-defining Relative Clauses" },
  { id: 39, question: "He works _____ than anyone else in the department.", options: ["hard", "harder", "hardest", "more hard"], answer: 1, topic: "Comparatives" },
  { id: 40, question: "She had her car _____ last weekend.", options: ["repair", "repaired", "repairing", "to repair"], answer: 1, topic: "Causative Have" },
  { id: 41, question: "We should have the documents _____ before the meeting.", options: ["translate", "translated", "translating", "to translate"], answer: 1, topic: "Causative" },
  { id: 42, question: "He is unlikely _____ the offer.", options: ["accept", "accepting", "to accept", "to accepting"], answer: 2, topic: "Infinitive" },
  { id: 43, question: "The problem could _____ if we had acted sooner.", options: ["avoid", "have avoided", "have been avoided", "be avoiding"], answer: 2, topic: "Modal Passive" },
  { id: 44, question: "Much as I _____ to help, I simply don't have enough time.", options: ["would like", "like", "liked", "will like"], answer: 0, topic: "Concession" },
  { id: 45, question: "Only after the meeting _____ the seriousness of the problem.", options: ["we understood", "did we understand", "we did understand", "understood we"], answer: 1, topic: "Inversion" },
  { id: 46, question: "She denied _____ the instructions.", options: ["to ignore", "ignore", "ignoring", "to ignoring"], answer: 2, topic: "Gerund" },
  { id: 47, question: "If it weren't for your help, I _____ able to finish this.", options: ["wouldn't be", "wouldn't have been", "won't be", "wasn't"], answer: 0, topic: "Second Conditional" },
  { id: 48, question: "The candidate is expected _____ the election.", options: ["win", "winning", "to win", "to winning"], answer: 2, topic: "Reporting Structures" },
  { id: 49, question: "Rarely _____ such a talented performer.", options: ["I have seen", "have I seen", "I saw", "did I saw"], answer: 1, topic: "Inversion" },
  { id: 50, question: "It was the first time I _____ such an impressive presentation.", options: ["had seen", "have seen", "saw", "see"], answer: 0, topic: "Past Perfect" },
];

export default b2Questions;
