const c1Questions = [
  { id: 1, question: "Had I ___ the warning, I would have acted differently.", options: ["known", "know", "knew", "knowing"], answer: 0, topic: "Inverted third conditional" },
  { id: 2, question: "Were the company ___ its policy, many users would complain.", options: ["change", "to change", "changed", "changing"], answer: 1, topic: "Inverted second conditional" },
  { id: 3, question: "Should you ___ any problems, contact support immediately.", options: ["experience", "experienced", "experiencing", "to experiencing"], answer: 0, topic: "Inverted conditional" },
  { id: 4, question: "Rarely ___ a solution so elegant.", options: ["we encounter", "do we encounter", "we do encounter", "encounter we"], answer: 1, topic: "Inversion" },
  { id: 5, question: "Seldom ___ such detailed evidence.", options: ["have researchers found", "researchers have found", "did researchers found", "researchers found have"], answer: 0, topic: "Inversion" },
  { id: 6, question: "Not until the final chapter ___ the connection.", options: ["I understood", "did I understand", "I did understand", "understood I"], answer: 1, topic: "Inversion" },
  { id: 7, question: "Little ___ that the decision would change everything.", options: ["they knew", "did they know", "they did know", "knew they"], answer: 1, topic: "Inversion" },
  { id: 8, question: "Only after reviewing the data ___ the error.", options: ["we noticed", "did we notice", "we did notice", "noticed we"], answer: 1, topic: "Inversion" },
  { id: 9, question: "No sooner had the announcement been made ___ the market reacted.", options: ["when", "than", "that", "then"], answer: 1, topic: "No sooner...than" },
  { id: 10, question: "Hardly had the project started ___ funding was reduced.", options: ["than", "when", "that", "then"], answer: 1, topic: "Hardly...when" },
  { id: 11, question: "The proposal, ___ initially rejected, was later adopted.", options: ["having been", "which having been", "was", "that was being"], answer: 0, topic: "Perfect participle passive" },
  { id: 12, question: "___ the evidence, the committee postponed its decision.", options: ["Having reviewed", "Reviewed", "To reviewing", "Review"], answer: 0, topic: "Perfect participle" },
  { id: 13, question: "The results ___, the researchers began drafting the paper.", options: ["were confirmed", "confirmed", "having confirmed", "confirming"], answer: 1, topic: "Absolute/participial construction" },
  { id: 14, question: "He is thought ___ the original manuscript.", options: ["to have destroyed", "to destroy", "destroying", "destroyed"], answer: 0, topic: "Perfect infinitive" },
  { id: 15, question: "She appears ___ the implications already.", options: ["to understand", "to have understood", "understanding", "understood"], answer: 1, topic: "Perfect infinitive" },
  { id: 16, question: "The company is reported ___ significant losses last year.", options: ["to incur", "to have incurred", "incurring", "incurred"], answer: 1, topic: "Reporting structure" },
  { id: 17, question: "I would sooner you ___ the matter privately.", options: ["discuss", "discussed", "had discussed", "will discuss"], answer: 1, topic: "Would sooner" },
  { id: 18, question: "I'd rather he ___ informed us before publishing the report.", options: ["has", "had", "would have", "will have"], answer: 1, topic: "Would rather + past perfect" },
  { id: 19, question: "It's high time the authorities ___ action.", options: ["take", "took", "have taken", "will take"], answer: 1, topic: "It's high time" },
  { id: 20, question: "She speaks as though she ___ personally involved.", options: ["were", "is", "has been", "would be"], answer: 0, topic: "As though" },
  { id: 21, question: "He talks as if he ___ the answer all along.", options: ["knows", "knew", "had known", "would know"], answer: 2, topic: "As if + past perfect" },
  { id: 22, question: "I wish the committee ___ more transparent from the start.", options: ["were", "had been", "would be", "is"], answer: 1, topic: "Wish + past perfect" },
  { id: 23, question: "If only we ___ the implications sooner.", options: ["realised", "had realised", "would realise", "realise"], answer: 1, topic: "If only" },
  { id: 24, question: "It is imperative that every applicant ___ the declaration.", options: ["signs", "sign", "signed", "to sign"], answer: 1, topic: "Mandative subjunctive" },
  { id: 25, question: "The board recommended that the policy ___ immediately.", options: ["is revised", "be revised", "was revised", "to revise"], answer: 1, topic: "Subjunctive passive" },
  { id: 26, question: "He objected to ___ responsible for the error.", options: ["be", "being", "have been", "to be"], answer: 1, topic: "Gerund after preposition" },
  { id: 27, question: "There is little point in ___ the same argument again.", options: ["repeat", "to repeat", "repeating", "repeated"], answer: 2, topic: "Gerund after preposition" },
  { id: 28, question: "She was on the verge of ___ her resignation.", options: ["submit", "to submit", "submitting", "submitted"], answer: 2, topic: "Gerund pattern" },
  { id: 29, question: "The findings are consistent with ___ previously reported.", options: ["what was", "what being", "that was", "which being"], answer: 0, topic: "Complex complement" },
  { id: 30, question: "The extent to ___ the policy succeeded remains disputed.", options: ["that", "which", "what", "where"], answer: 1, topic: "Complex relative" },
  { id: 31, question: "The person ___ I assumed was responsible has resigned.", options: ["who", "whom", "which", "whose"], answer: 0, topic: "Complex relative clause" },
  { id: 32, question: "Whatever the outcome ___, we must prepare.", options: ["will be", "may be", "is being", "would be"], answer: 1, topic: "Free relative clause" },
  { id: 33, question: "Much as I ___ the proposal, I cannot support its implementation.", options: ["admire", "am admiring", "have admire", "would admire"], answer: 0, topic: "Concessive clause" },
  { id: 34, question: "Try as he ___, he could not reproduce the result.", options: ["may", "might", "would", "did"], answer: 1, topic: "Concessive inversion" },
  { id: 35, question: "Be that as it ___, the deadline remains unchanged.", options: ["is", "be", "was", "will"], answer: 0, topic: "Fixed subjunctive expression" },
  { id: 36, question: "The report is anything but ___.", options: ["conclusive", "conclusively", "conclude", "conclusion"], answer: 0, topic: "Fixed expression" },
  { id: 37, question: "The evidence is far from ___.", options: ["decisive", "deciding", "decide", "decision"], answer: 0, topic: "Fixed expression" },
  { id: 38, question: "The issue is by no means ___.", options: ["resolve", "resolved", "resolving", "resolution"], answer: 1, topic: "Fixed expression" },
  { id: 39, question: "So complex ___ the system that few users understood it.", options: ["was", "were", "did", "has"], answer: 0, topic: "So...that inversion" },
  { id: 40, question: "Such was the demand ___ the service crashed.", options: ["than", "that", "which", "as"], answer: 1, topic: "Such...that" },
  { id: 41, question: "What the committee failed to consider ___ the long-term cost.", options: ["were", "was", "have been", "are"], answer: 1, topic: "Cleft structure" },
  { id: 42, question: "It was not the price but the reliability ___ convinced me.", options: ["which", "that", "what", "where"], answer: 1, topic: "Cleft structure" },
  { id: 43, question: "The more carefully the data are examined, ___ the pattern becomes.", options: ["clearer", "the clearer", "clearest", "more clear"], answer: 1, topic: "Double comparative" },
  { id: 44, question: "The policy is likely ___ significant changes.", options: ["to undergo", "undergo", "undergoing", "to undergoing"], answer: 0, topic: "Adjective + infinitive" },
  { id: 45, question: "There is no reason ___ the figures should be inaccurate.", options: ["believing", "to believe", "believe", "for believe"], answer: 1, topic: "Infinitive complement" },
  { id: 46, question: "She is believed ___ the decision in advance.", options: ["to know", "to have known", "knowing", "known"], answer: 1, topic: "Perfect infinitive" },
  { id: 47, question: "The minister denied ___ any prior knowledge of the proposal.", options: ["have", "to have", "having", "had"], answer: 2, topic: "Gerund" },
  { id: 48, question: "The evidence leaves little doubt that the figures ___ manipulated.", options: ["were", "have been", "had been", "are being"], answer: 2, topic: "Past perfect passive" },
  { id: 49, question: "It is essential that the documents ___ before the hearing.", options: ["are submitted", "be submitted", "were submitted", "to submit"], answer: 1, topic: "Subjunctive passive" },
  { id: 50, question: "Much as I ___ the approach, the evidence does not support it.", options: ["admire", "am admiring", "would admire", "have admired"], answer: 0, topic: "Concessive clause" },
];

export default c1Questions;
