const c2Questions = [
  { id: 1, question: "Were it not for the final clause, the agreement ___ legally binding.", options: ["would be", "will be", "would have been", "is"], answer: 0, topic: "Inverted conditional" },
  { id: 2, question: "Had it not been for her intervention, the dispute ___ far longer.", options: ["would continue", "would have continued", "will continue", "continued"], answer: 1, topic: "Inverted third conditional" },
  { id: 3, question: "Should the evidence ___ otherwise, the conclusion would need revision.", options: ["prove", "proved", "proving", "to prove"], answer: 0, topic: "Inverted conditional" },
  { id: 4, question: "Never before ___ such a comprehensive account of the issue.", options: ["we had seen", "had we seen", "we saw", "did we saw"], answer: 1, topic: "Advanced inversion" },
  { id: 5, question: "At no point ___ that the figures were inaccurate.", options: ["the auditors suggested", "did the auditors suggest", "the auditors did suggest", "suggested the auditors"], answer: 1, topic: "Advanced inversion" },
  { id: 6, question: "Under no circumstances ___ the data be released publicly.", options: ["the committee would allow", "would the committee allow", "the committee allow", "allow the committee"], answer: 1, topic: "Negative inversion" },
  { id: 7, question: "Only by examining the original records ___ the discrepancy be explained.", options: ["it can", "can it", "it could", "could it be"], answer: 1, topic: "Only + inversion" },
  { id: 8, question: "So intricate ___ the legal framework that even specialists disagreed.", options: ["was", "were", "did", "has"], answer: 0, topic: "So + adjective inversion" },
  { id: 9, question: "Such ___ the complexity of the case that proceedings lasted years.", options: ["was", "were", "did", "has"], answer: 0, topic: "Such + noun inversion" },
  { id: 10, question: "The manuscript is thought ___ several earlier drafts.", options: ["to contain", "to have contained", "containing", "contained"], answer: 1, topic: "Perfect infinitive" },
  { id: 11, question: "He is alleged ___ confidential material to the press.", options: ["to leak", "to have leaked", "leaking", "leaked"], answer: 1, topic: "Reporting passive" },
  { id: 12, question: "The policy is understood ___ under review for months.", options: ["to be", "to have been", "being", "been"], answer: 1, topic: "Reporting passive" },
  { id: 13, question: "The witnesses claimed ___ the vehicle before the incident.", options: ["to see", "to have seen", "seeing", "seen"], answer: 1, topic: "Perfect infinitive" },
  { id: 14, question: "I would just as soon you ___ the issue until tomorrow.", options: ["leave", "left", "had left", "would leave"], answer: 1, topic: "Would just as soon" },
  { id: 15, question: "If he had not ignored the evidence, the outcome ___ different now.", options: ["would be", "would have been", "will be", "is"], answer: 0, topic: "Mixed conditional" },
  { id: 16, question: "If the system were more robust, it ___ so frequently last year.", options: ["would not have failed", "would not fail", "will not have failed", "did not fail"], answer: 0, topic: "Mixed conditional" },
  { id: 17, question: "If she ___ more cautious then, she would not be facing the inquiry now.", options: ["were", "had been", "would be", "has been"], answer: 1, topic: "Mixed conditional" },
  { id: 18, question: "I wish I ___ the implications before I signed.", options: ["understood", "had understood", "would understand", "have understood"], answer: 1, topic: "Wish + past perfect" },
  { id: 19, question: "If only the authorities ___ the warning seriously at the time.", options: ["took", "had taken", "would take", "take"], answer: 1, topic: "If only" },
  { id: 20, question: "It is high time the entire procedure ___.", options: ["is reviewed", "were reviewed", "will be reviewed", "has reviewed"], answer: 1, topic: "Mandative past" },
  { id: 21, question: "The committee insisted that the report ___ before publication.", options: ["be revised", "is revised", "was revising", "to revise"], answer: 0, topic: "Subjunctive passive" },
  { id: 22, question: "It is vital that no assumption ___ without evidence.", options: ["is made", "be made", "was made", "to make"], answer: 1, topic: "Subjunctive passive" },
  { id: 23, question: "The judge ordered that the documents ___ immediately.", options: ["are released", "be released", "were releasing", "to release"], answer: 1, topic: "Subjunctive" },
  { id: 24, question: "The evidence is such ___ it cannot be dismissed.", options: ["as", "that", "which", "what"], answer: 1, topic: "Such...that" },
  { id: 25, question: "He was so convinced of his argument ___ he ignored the counterevidence.", options: ["that", "as", "which", "than"], answer: 0, topic: "So...that" },
  { id: 26, question: "Much as one ___ disagree, the data are consistent.", options: ["may", "might", "would", "could have"], answer: 0, topic: "Concessive clause" },
  { id: 27, question: "Try as she ___, she could not reproduce the result.", options: ["might", "may", "would", "did"], answer: 0, topic: "Concessive inversion" },
  { id: 28, question: "However carefully the experiment ___ designed, uncertainty remains.", options: ["is", "be", "was being", "would be"], answer: 0, topic: "Concessive clause" },
  { id: 29, question: "Whatever the committee ___, the deadline cannot change.", options: ["decides", "may decide", "would decide", "decided"], answer: 1, topic: "Free relative" },
  { id: 30, question: "The person to ___ the documents were addressed could not be identified.", options: ["who", "whom", "which", "whose"], answer: 1, topic: "Formal relative clause" },
  { id: 31, question: "The grounds on ___ the decision was based were later challenged.", options: ["that", "which", "what", "where"], answer: 1, topic: "Formal relative clause" },
  { id: 32, question: "The extent to ___ the reform succeeded is difficult to quantify.", options: ["that", "which", "what", "where"], answer: 1, topic: "Formal relative clause" },
  { id: 33, question: "The proposal, the merits of ___ were widely debated, was rejected.", options: ["which", "that", "what", "whose"], answer: 0, topic: "Formal relative clause" },
  { id: 34, question: "The findings, ___ independently verified, were considered conclusive.", options: ["having been", "have been", "were", "that were"], answer: 0, topic: "Perfect participle passive" },
  { id: 35, question: "___ all alternatives, the panel reached its conclusion.", options: ["Having considered", "Considered", "To consider", "Considering had"], answer: 0, topic: "Perfect participle" },
  { id: 36, question: "The data ___, no further action was taken.", options: ["being archived", "having been archived", "were archived", "archived"], answer: 1, topic: "Absolute construction" },
  { id: 37, question: "There ___ no reliable evidence, the claim was dismissed.", options: ["being", "having been", "was", "be"], answer: 0, topic: "Absolute construction" },
  { id: 38, question: "The theory is not so much wrong ___ inadequately supported.", options: ["than", "as", "that", "which"], answer: 1, topic: "Not so much...as" },
  { id: 39, question: "He is anything but ___ to criticism.", options: ["receptive", "reception", "receptively", "receive"], answer: 0, topic: "Fixed expression" },
  { id: 40, question: "The conclusion is all but ___.", options: ["certain", "certainty", "certainly", "certify"], answer: 0, topic: "Fixed expression" },
  { id: 41, question: "The distinction is far from ___.", options: ["clear-cut", "clearly-cut", "clear cutting", "cleared"], answer: 0, topic: "Fixed expression" },
  { id: 42, question: "It was the lack of evidence, rather than the theory itself, ___ caused concern.", options: ["which", "that", "what", "where"], answer: 1, topic: "Cleft structure" },
  { id: 43, question: "What remains unclear ___ why the figures changed.", options: ["are", "is", "have", "were"], answer: 1, topic: "Cleft structure" },
  { id: 44, question: "It is the underlying assumption ___ needs to be reconsidered.", options: ["what", "which", "that", "where"], answer: 2, topic: "Cleft structure" },
  { id: 45, question: "The more sophisticated the model, ___ the assumptions become.", options: ["the more hidden", "more hidden", "the most hidden", "hidden"], answer: 0, topic: "Double comparative" },
  { id: 46, question: "Little did they realise how fundamentally the discovery ___ the field.", options: ["would change", "had changed", "changes", "has changed"], answer: 0, topic: "Inversion" },
  { id: 47, question: "No sooner had the results been published ___ criticism began.", options: ["when", "than", "that", "as"], answer: 1, topic: "No sooner...than" },
  { id: 48, question: "Scarcely had the negotiations begun ___ a new obstacle emerged.", options: ["than", "when", "that", "as"], answer: 1, topic: "Scarcely...when" },
  { id: 49, question: "Not only was the proposal rejected, ___ it was also removed from the agenda.", options: ["but", "and", "so", "yet"], answer: 0, topic: "Correlative inversion" },
  { id: 50, question: "The committee denied ___ prior knowledge of the discrepancy.", options: ["to have", "having", "have", "had"], answer: 1, topic: "Gerund" },
];

export default c2Questions;
